### ISSUE TITLE
overlay manager to-do list

### ISSUE THREAD

**Issue by cyperdark** [tosuapp/tosu#191]
- [x] Move counter settings to separated folder
- [x] https://github.com/KotRikD/tosu/issues/78
- [x] improve settings builder
- [x] add textarea as option
- [x] add commands option
- [x] add button option
